
export default new Map([
["src/content/pages/dr-peter-huber.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fdr-peter-huber.mdx&astroContentModuleFlag=true")],
["src/content/pages/faqs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Ffaqs.mdx&astroContentModuleFlag=true")],
["src/content/pages/home.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fhome.mdx&astroContentModuleFlag=true")],
["src/content/pages/dsgvo.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fdsgvo.mdx&astroContentModuleFlag=true")],
["src/content/pages/impressum.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fimpressum.mdx&astroContentModuleFlag=true")],
["src/content/pages/kontakt.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fkontakt.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen.mdx&astroContentModuleFlag=true")],
["src/content/pages/ordination.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fordination.mdx&astroContentModuleFlag=true")],
["src/content/pages/wahlarzt.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fwahlarzt.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/24-stunden-blutdruck.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2F24-stunden-blutdruck.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/abdomen-nieren-sonographie.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fabdomen-nieren-sonographie.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/echokardiographie.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fechokardiographie.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/anamnese-und-untersuchung.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fanamnese-und-untersuchung.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/ergometrie.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fergometrie.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/ruhe-ekg.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fruhe-ekg.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/langzeit-ekg.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Flangzeit-ekg.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/polygraphie.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fpolygraphie.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/spirometrie.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fspirometrie.mdx&astroContentModuleFlag=true")],
["src/content/pages/leistungen/ultraschall-halsschlagader.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fleistungen%2Fultraschall-halsschlagader.mdx&astroContentModuleFlag=true")]]);
		