
import __ASTRO_IMAGE_IMPORT_Z1FKOIe from "src/assets/images/dr-peter-huber.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fdr-peter-huber.mdx";
import __ASTRO_IMAGE_IMPORT_ZgH65a from "src/assets/images/leistungen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fleistungen.mdx";
import __ASTRO_IMAGE_IMPORT_tuOvj from "src/assets/images/faq.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Ffaqs.mdx";
import __ASTRO_IMAGE_IMPORT_1lnYt8 from "src/assets/images/kontakt.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fkontakt.mdx";
import __ASTRO_IMAGE_IMPORT_mNtaN from "src/assets/images/wahlarzt-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fwahlarzt.mdx";
import __ASTRO_IMAGE_IMPORT_Zuac48 from "src/assets/images/home.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fhome.mdx";
import __ASTRO_IMAGE_IMPORT_Z1Hjy2H from "src/assets/images/home-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fhome.mdx";
export default new Map([["src/assets/images/dr-peter-huber.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fdr-peter-huber.mdx", __ASTRO_IMAGE_IMPORT_Z1FKOIe], ["src/assets/images/leistungen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fleistungen.mdx", __ASTRO_IMAGE_IMPORT_ZgH65a], ["src/assets/images/faq.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Ffaqs.mdx", __ASTRO_IMAGE_IMPORT_tuOvj], ["src/assets/images/kontakt.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fkontakt.mdx", __ASTRO_IMAGE_IMPORT_1lnYt8], ["src/assets/images/wahlarzt-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fwahlarzt.mdx", __ASTRO_IMAGE_IMPORT_mNtaN], ["src/assets/images/home.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fhome.mdx", __ASTRO_IMAGE_IMPORT_Zuac48], ["src/assets/images/home-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fhome.mdx", __ASTRO_IMAGE_IMPORT_Z1Hjy2H]]);
		